build:
	wasm-pack build
tree:
	cargo tree
generate:
	npm --prefix ./frontend install
clean:
	npm --prefix ./frontend cache clean --force
run:
	npm --prefix ./frontend run dev
crate-next-app:
	npx create-next-app@latest frontend --no-tailwind --no-turbopack --yes