image: lzpel/home@sha256:b80b2b923e2d5832a72f86b4b30e7bcc110dae1d70e80404cd709eaa58ced340

variables:
  NODE_ENV: production
  NEXT_PUBLIC_REPO: $CI_PROJECT_NAME
  NEXT_DIR_PATH: frontend # subdir or .
  NEXT_EXPORT_DIR: public # 出力先を GitLab Pages の仕様に合わせる（public/ フォルダに）

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next/cache/

pages:
  stage: deploy
  script:
    - mkdir -p $NEXT_DIR_PATH/$NEXT_EXPORT_DIR
    - printenv > $NEXT_DIR_PATH/$NEXT_EXPORT_DIR/env
    - export http_proxy="$HTTP_PROXY"
    - export https_proxy="$HTTPS_PROXY"
    - export CARGO_HTTP_PROXY="$HTTP_PROXY"
    - export CARGO_HTTPS_PROXY="$HTTPS_PROXY"
    - make generate
    - cd $NEXT_DIR_PATH
    - |
      if [ -f yarn.lock ]; then
        yarn install
        yarn build
        yarn export -o $NEXT_EXPORT_DIR
      else
        npm ci
        npx --no-install next build
        npx --no-install next export -o $NEXT_EXPORT_DIR
      fi
  artifacts:
    paths:
      - $NEXT_DIR_PATH/$NEXT_EXPORT_DIR
    expire_in: 1 hour