image: lzpel/home@sha256:b80b2b

variables:
  NODE_ENV: production
  NEXT_PUBLIC_REPO: $CI_PROJECT_NAME
  NEXT_DIR_PATH: frontend # subdir or .
  NEXT_EXPORT_DIR: public # 出力先を GitLab Pages の仕様に合わせる（public/ フォルダに）

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next/cache/

pages:
  stage: deploy
  script:
    - make generate
    - cd $NEXT_DIR_PATH
    - |
      if [ -f yarn.lock ]; then
        yarn install
        yarn build
        yarn export -o $NEXT_EXPORT_DIR
      else
        npm ci
        npx --no-install next build
        npx --no-install next export -o $NEXT_EXPORT_DIR
      fi
  artifacts:
    paths:
      - $NEXT_DIR_PATH/$NEXT_EXPORT_DIR
    expire_in: 1 hour