[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mandolin = { path = "../.." }
wasm-bindgen = "*"
console_error_panic_hook = "*"
serde_yaml = "*"